// src/app/models/sales-plan-routes.model.ts

export const routesByZone: { [zone: string]: string[] } = {
    ZONE_BOGOTA: [
      'ROUTE_BOGOTA_NORTE',
      'ROUTE_BOGOTA_SUR',
      'ROUTE_BOGOTA_CHAPINERO',
      'ROUTE_BOGOTA_ENGATIVA',
      'ROUTE_BOGOTA_KENNEDY',
      'ROUTE_BOGOTA_USAQUEN'
    ],
    ZONE_MEDELLIN: [
      'ROUTE_MEDELLIN_CENTRO',
      'ROUTE_MEDELLIN_BELEN',
      'ROUTE_MEDELLIN_EL_POBLADO',
      'ROUTE_MEDELLIN_CASTILLA',
      'ROUTE_MEDELLIN_ARANJUEZ',
      'ROUTE_MEDELLIN_LA_AMERICA'
    ],
    ZONE_CALI: [
      'ROUTE_CALI_NORTE',
      'ROUTE_CALI_SUR',
      'ROUTE_CALI_AGUABLANCA',
      'ROUTE_CALI_SAN_FERNANDO',
      'ROUTE_CALI_SILOE',
      'ROUTE_CALI_LA_FLORESTA'
    ],
    ZONE_BARRANQUILLA: [
      'ROUTE_BARRANQUILLA_NORTE',
      'ROUTE_BARRANQUILLA_SUR',
      'ROUTE_BARRANQUILLA_EL_PRADO',
      'ROUTE_BARRANQUILLA_SANTO_DOMINGO',
      'ROUTE_BARRANQUILLA_SIMON_BOLIVAR',
      'ROUTE_BARRANQUILLA_LA_LUZ'
    ],
    ZONE_NEW_YORK: [
      'ROUTE_NY_BROOKLYN',
      'ROUTE_NY_QUEENS',
      'ROUTE_NY_MANHATTAN',
      'ROUTE_NY_BRONX',
      'ROUTE_NY_STATEN_ISLAND',
      'ROUTE_NY_HARLEM'
    ],
    ZONE_CALIFORNIA: [
      'ROUTE_CA_SF',
      'ROUTE_CA_LA',
      'ROUTE_CA_SAN_DIEGO',
      'ROUTE_CA_SAN_JOSE',
      'ROUTE_CA_SACRAMENTO',
      'ROUTE_CA_OAKLAND'
    ],
    ZONE_TEXAS: [
      'ROUTE_TX_DALLAS',
      'ROUTE_TX_HOUSTON',
      'ROUTE_TX_AUSTIN',
      'ROUTE_TX_SAN_ANTONIO',
      'ROUTE_TX_EL_PASO',
      'ROUTE_TX_FORT_WORTH'
    ],
    ZONE_FLORIDA: [
      'ROUTE_FL_MIAMI',
      'ROUTE_FL_ORLANDO',
      'ROUTE_FL_TAMPA',
      'ROUTE_FL_JACKSONVILLE',
      'ROUTE_FL_NAPLES',
      'ROUTE_FL_FORT_LAUDERDALE'
    ]
  };
  
  export const zoneToCountryMap: { [zone: string]: string } = {
    ZONE_BOGOTA: 'COVERAGE_COLOMBIA',
    ZONE_MEDELLIN: 'COVERAGE_COLOMBIA',
    ZONE_CALI: 'COVERAGE_COLOMBIA',
    ZONE_BARRANQUILLA: 'COVERAGE_COLOMBIA',
    ZONE_NEW_YORK: 'COVERAGE_USA',
    ZONE_CALIFORNIA: 'COVERAGE_USA',
    ZONE_TEXAS: 'COVERAGE_USA',
    ZONE_FLORIDA: 'COVERAGE_USA'
  };