name: Deploy Angular App to S3

on:
  pull_request:
    branches: [stage]
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    if: github.event.pull_request.head.ref == 'develop' && github.event.pull_request.base.ref == 'stage'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Run unit tests
        run: ng test --watch=false --code-coverage

      - name: Ensure tests passed
        run: |
          if [ $? -ne 0 ]; then
            echo "Unit tests failed"
            exit 1
          fi

      - name: Instalar nyc
        run: npm install nyc --save-dev

      - name: Ejecutar pruebas con cobertura
        run: npx nyc --reporter=lcov --reporter=text-summary ng test --watch=false

      - name: Verificar cobertura mínima
        run: npx nyc check-coverage --statements=70 --branches=70 --functions=70 --lines=70

      - name: Build Angular app
        run: ng build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List build output
        run: ls -la ./dist

      - name: Deploy to S3
        run: aws s3 sync ./dist/proyecto-final-web s3://fe-web-v1 --delete
