name: Tests and Coverage Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Ejecutar pruebas unitarias con coverage
        run: ng test --code-coverage --watch=false --code-coverage

      - name: Validar coverage general (mínimo 71%)
        run: |
          # Buscar el archivo coverage-summary.json en cualquier subdirectorio
          FILE=$(find ./coverage -type f -name coverage-summary.json | head -n 1)
          echo "Usando archivo de coverage: $FILE"

          # Se recorre el archivo JSON y se valida la cobertura total
          node -e "
          const coverage = require('$FILE').total;
          const required = 71;
          let failed = false;
          console.log('Coverage total:');
          console.log(\`  Statements: \${coverage.statements.pct}%\`);
          console.log(\`  Branches: \${coverage.branches.pct}%\`);
          console.log(\`  Functions: \${coverage.functions.pct}%\`);
          console.log(\`  Lines: \${coverage.lines.pct}%\`);
          if (
            coverage.statements.pct < required ||
            coverage.branches.pct < required ||
            coverage.functions.pct < required ||
            coverage.lines.pct < required
          ) {
            console.error(\`Coverage total es inferior al umbral requerido de \${required}%\`);
            failed = true;
          }
          if (failed) process.exit(1);
          "
