name: Tests and Coverage Develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Ejecutar pruebas unitarias con coverage
        run: npm run test -- --watch=false --code-coverage

      - name: Validar umbral de coverage (mínimo 71%)
        run: |
          COVERAGE=$(node -p "require('./coverage/coverage-summary.json').total.lines.pct")
          echo "Coverage actual: $COVERAGE%"
          if (( $(echo "$COVERAGE < 71" | bc -l) )); then
            echo "Error: La cobertura ($COVERAGE%) es inferior al 71% requerido."
            exit 1
          else
            echo "La cobertura cumple con el mínimo requerido."
          fi
